<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class WargaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('warga')->insert([
            [
                'nik'               => '1020304050607101',
                'no_kk'             => '1122334455667701',
                'nama'              => 'Cristiano Ronaldo',
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'Madeira',
                'tanggal_lahir'     => '05 February 1985',
                'agama'             => 'Katolik',
                'pekerjaan'         => 'Atlit',
                'status_kawin'      => 'Kawin',
                'no_telp'           => '081234567890',
                'peran'             => 'Kepala Keluarga',
                'status'            => 'Aktif',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nik'               => '1020304050607102',
                'no_kk'             => '1122334455667701',
                'nama'              => 'Georgina Rodriguez',
                'jenis_kelamin'     => 'Perempuan',
                'tempat_lahir'      => 'Buenos Aires',
                'tanggal_lahir'     => '27 January 1994',
                'agama'             => 'Katolik',
                'pekerjaan'         => 'Artis',
                'status_kawin'      => 'Kawin',
                'no_telp'           => '081234567890',
                'peran'             => 'Anggota Keluarga',
                'status'            => 'Aktif',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nik'               => '1020304050607103',
                'no_kk'             => '1122334455667701',
                'nama'              => 'Cristiano Ronaldo Junior',
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'San Diego',
                'tanggal_lahir'     => '17 June 2010',
                'agama'             => 'Katolik',
                'pekerjaan'         => 'Pelajar/Mahasiswa',
                'status_kawin'      => 'Belum Kawin',
                'no_telp'           => '081234567890',
                'peran'             => 'Anggota Keluarga',
                'status'            => 'Aktif',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nik'               => '1020304050607104',
                'no_kk'             => '1122334455667701',
                'nama'              => 'Eva Maria Dos Santos',
                'jenis_kelamin'     => 'Perempuan',
                'tempat_lahir'      => 'San Diego',
                'tanggal_lahir'     => '08 June 2017',
                'agama'             => 'Katolik',
                'pekerjaan'         => 'Pelajar/Mahasiswa',
                'status_kawin'      => 'Belum Kawin',
                'no_telp'           => '081234567890',
                'peran'             => 'Anggota Keluarga',
                'status'            => 'Aktif',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nik'               => '1020304050607105',
                'no_kk'             => '1122334455667701',
                'nama'              => 'Mateo Ronaldo',
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'San Diego',
                'tanggal_lahir'     => '08 June 2017',
                'agama'             => 'Katolik',
                'pekerjaan'         => 'Pelajar/Mahasiswa',
                'status_kawin'      => 'Belum Kawin',
                'no_telp'           => '081234567890',
                'peran'             => 'Anggota Keluarga',
                'status'            => 'Aktif',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nik'               => '1020304050607201',
                'no_kk'             => '1122334455667702',
                'nama'              => 'Lionel Messi',
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'Rosario',
                'tanggal_lahir'     => '24 June 1987',
                'agama'             => 'Katolik',
                'pekerjaan'         => 'Atlit',
                'status_kawin'      => 'Kawin',
                'no_telp'           => '081234567890',
                'peran'             => 'Kepala Keluarga',
                'status'            => 'Aktif',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nik'               => '1020304050607202',
                'no_kk'             => '1122334455667702',
                'nama'              => 'Antonella Roccuzzo',
                'jenis_kelamin'     => 'Perempuan',
                'tempat_lahir'      => 'Rosario',
                'tanggal_lahir'     => '26 February 1988',
                'agama'             => 'Katolik',
                'pekerjaan'         => 'Artis',
                'status_kawin'      => 'Kawin',
                'no_telp'           => '081234567890',
                'peran'             => 'Anggota Keluarga',
                'status'            => 'Aktif',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nik'               => '1020304050607203',
                'no_kk'             => '1122334455667702',
                'nama'              => 'Thiago Messi',
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'Barcelona',
                'tanggal_lahir'     => '02 November 2012',
                'agama'             => 'Katolik',
                'pekerjaan'         => 'Pelajar/Mahasiswa',
                'status_kawin'      => 'Belum Kawin',
                'no_telp'           => '081234567890',
                'peran'             => 'Anggota Keluarga',
                'status'            => 'Aktif',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nik'               => '1020304050607204',
                'no_kk'             => '1122334455667702',
                'nama'              => 'Mateo Messi',
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'Barcelona',
                'tanggal_lahir'     => '11 September 2015',
                'agama'             => 'Katolik',
                'pekerjaan'         => 'Pelajar/Mahasiswa',
                'status_kawin'      => 'Belum Kawin',
                'no_telp'           => '081234567890',
                'peran'             => 'Anggota Keluarga',
                'status'            => 'Aktif',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nik'               => '1020304050607205',
                'no_kk'             => '1122334455667702',
                'nama'              => 'Ciro Messi',
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'Barcelona',
                'tanggal_lahir'     => '10 March 2018',
                'agama'             => 'Katolik',
                'pekerjaan'         => 'Pelajar/Mahasiswa',
                'status_kawin'      => 'Belum Kawin',
                'no_telp'           => '081234567890',
                'peran'             => 'Anggota Keluarga',
                'status'            => 'Aktif',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nik'               => '1020304050607301',
                'no_kk'             => '1122334455667703',
                'nama'              => 'Neymar Junior',
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'Mogi das Cruzes',
                'tanggal_lahir'     => '05 February 1992',
                'agama'             => 'Katolik',
                'pekerjaan'         => 'Atlit',
                'status_kawin'      => 'Kawin',
                'no_telp'           => '081234567890',
                'peran'             => 'Kepala Keluarga',
                'status'            => 'Aktif',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nik'               => '1020304050607302',
                'no_kk'             => '1122334455667703',
                'nama'              => 'Bruna Biancardi',
                'jenis_kelamin'     => 'Perempuan',
                'tempat_lahir'      => 'Sao Paulo',
                'tanggal_lahir'     => '15 April 1994',
                'agama'             => 'Katolik',
                'pekerjaan'         => 'Artis',
                'status_kawin'      => 'Kawin',
                'no_telp'           => '081234567890',
                'peran'             => 'Anggota Keluarga',
                'status'            => 'Aktif',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nik'               => '1020304050607303',
                'no_kk'             => '1122334455667703',
                'nama'              => 'Davi Lucca da Silva Santos',
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'Sao Paulo',
                'tanggal_lahir'     => '24 August 2011',
                'agama'             => 'Katolik',
                'pekerjaan'         => 'Pelajar/Mahasiswa',
                'status_kawin'      => 'Belum Kawin',
                'no_telp'           => '081234567890',
                'peran'             => 'Anggota Keluarga',
                'status'            => 'Aktif',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nik'               => '1020304050607401',
                'no_kk'             => '1122334455667704',
                'nama'              => 'Karim Benzema',
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'Lyon',
                'tanggal_lahir'     => '19 December 1987',
                'agama'             => 'Islam',
                'pekerjaan'         => 'Atlit',
                'status_kawin'      => 'Kawin',
                'no_telp'           => '081234567890',
                'peran'             => 'Kepala Keluarga',
                'status'            => 'Aktif',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nik'               => '1020304050607402',
                'no_kk'             => '1122334455667704',
                'nama'              => 'Cora Gauthier',
                'jenis_kelamin'     => 'Perempuan',
                'tempat_lahir'      => 'Martinique',
                'tanggal_lahir'     => '11 April 1989',
                'agama'             => 'Islam',
                'pekerjaan'         => 'Artis',
                'status_kawin'      => 'Kawin',
                'no_telp'           => '081234567890',
                'peran'             => 'Anggota Keluarga',
                'status'            => 'Aktif',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nik'               => '1020304050607403',
                'no_kk'             => '1122334455667704',
                'nama'              => 'Melia Benzema',
                'jenis_kelamin'     => 'Perempuan',
                'tempat_lahir'      => 'Madrid',
                'tanggal_lahir'     => '03 February 2014',
                'agama'             => 'Islam',
                'pekerjaan'         => 'Pelajar/Mahasiswa',
                'status_kawin'      => 'Belum Kawin',
                'no_telp'           => '081234567890',
                'peran'             => 'Anggota Keluarga',
                'status'            => 'Aktif',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nik'               => '1020304050607404',
                'no_kk'             => '1122334455667704',
                'nama'              => 'Ibrahim Benzema',
                'jenis_kelamin'     => 'Laki-laki',
                'tempat_lahir'      => 'Madrid',
                'tanggal_lahir'     => '05 May 2017',
                'agama'             => 'Islam',
                'pekerjaan'         => 'Pelajar/Mahasiswa',
                'status_kawin'      => 'Belum Kawin',
                'no_telp'           => '081234567890',
                'peran'             => 'Anggota Keluarga',
                'status'            => 'Aktif',
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
        ]);
    }
}
